[functions]
  directory = "netlify/functions"

[[redirects]]
  from   = "/api/notion"
  to     = "/.netlify/functions/notion-proxy"
  status = 200

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
